nome = input('Escreva seu nome: ')
cpf = input('Escreva seu CPF: ')
endereco = input('Escreva seu Endereço: ')
idade = input('Escreva sua idade: ')
altura = input('Escreva sua altura: ')
telefone = input('Escreva seu telefone: ')

print('Nome:', nome)
print('CPF:', cpf)
print('EndereÃ§o:', endereco)
print('Idade:', idade, 'anos')
print('Altura:', altura, 'metros')
print('Telefone:', telefone)
